sonar.projectKey=taskflow-api
sonar.projectName=taskflow-api
sonar.projectVersion=1.0
sonar.sources=server/src
sonar.tests=server/test,server/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
